# Notebook Agenda

In this notebook, we will cover the following topics:
NLP - Natural Language Processing
- Introduction to NLP

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Representing Text as numerical Data

In [3]:
simple_train = ["call you tonight", "Call me a cab", "Please call me... PLEASE!"]

In [4]:
# It will give all the unique words in the text and their count.
from sklearn.feature_extraction.text import CountVectorizer

# Initializing the CountVectorizer
vect = CountVectorizer()

# Sample text data
vect.fit(simple_train)
vect.get_feature_names_out()

array(['cab', 'call', 'me', 'please', 'tonight', 'you'], dtype=object)

In [5]:
# transform training data into a 'document-term matrix'
simple_train_dtm = vect.transform(simple_train)
simple_train_dtm.toarray()

array([[0, 1, 0, 0, 1, 1],
       [1, 1, 1, 0, 0, 0],
       [0, 1, 1, 2, 0, 0]])

In [6]:
# Dataframe
pd.DataFrame(simple_train_dtm.toarray(), columns=vect.get_feature_names_out())

   cab  call  me  please  tonight  you
0    0     1   0       0        1    1
1    1     1   1       0        0    0
2    0     1   1       2        0    0

In [ ]:
## Example text
simple_text = ["please dot call me a cab"]

simple_test_dtm = vect.transform(simple_text)
pd.DataFrame(simple_test_dtm.toarray(), columns=vect.get_feature_names_out())

   cab  call  me  please  tonight  you
0    1     1   1       1        0    0